package no.stormberry.sunapp.solar

import java.time.Instant
import java.time.LocalDate
import java.time.ZoneOffset
import kotlin.math.PI
import kotlin.math.acos
import kotlin.math.asin
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.floor
import kotlin.math.sin
import kotlin.math.tan

/**
 * Where the sun is, in radians, as SunCalc reports it.
 *
 * [azimuthRad] is measured from **south**, increasing westwards, which is the convention the
 * upstream library uses and not the compass convention most people expect. Anything rendering
 * a bearing has to add PI and normalise; that conversion belongs at the UI edge, not here,
 * because moving it into the port would break parity with the web app for no gain.
 */
data class SolarPosition(val altitudeRad: Double, val azimuthRad: Double)

/**
 * A literal Kotlin transcription of the solar half of SunCalc 1.8.0, the copy bundled at
 * `SunApp/suncalc.js` and served by sun.stormberry.as.
 *
 * **This is a port, not an implementation.** Every expression below is the minified original
 * with its names restored and nothing else changed: same constants, same operator ordering,
 * same single-pass algebra. That is a deliberate constraint rather than laziness. SunCalc is
 * an approximation that is self-inconsistent by up to roughly 0.2 deg of altitude at its own
 * reported crossings, so "improving" any line here makes the APK disagree with the web app
 * while looking more correct in isolation. The golden corpus in `suncalc-golden.csv` is
 * generated by running the actual `suncalc.js` under Node, so it enforces this to the
 * millisecond and will reject an upgrade to better astronomy as a regression.
 *
 * Three specific temptations, each of which has been tried and each of which breaks something:
 *
 *  1. **`kotlin.math.round` in [julianCycle].** JavaScript's `Math.round` is round-half-**up**;
 *     Kotlin's is round-half-to-**even**. They differ only at an exact tie, and SunCalc's
 *     `J0 = 9e-4` term shifts the argument off `.5` at essentially every real longitude, so
 *     the substitution passes 24 of the corpus's 25 cases silently. Case G25 exists solely
 *     because longitude -179.6760 on an even day counter is the one coordinate that lands on
 *     a true tie, where the two rules put solar noon a full day apart. Hence `floor(x + 0.5)`
 *     written out literally.
 *  2. **A defensive `coerceIn(-1.0, 1.0)` on the [hourAngle] `acos` argument.** That argument
 *     leaving [-1, 1] is not a numerical accident to be papered over: it *is* the detection of
 *     polar night and midnight sun. `acos` returning NaN is the signal that the sun never
 *     reaches the requested altitude that day. Clamping it manufactures a fake sunrise at
 *     solar noon. Case G13 (Longyearbyen at midsummer, all twelve angle events absent) is the
 *     pin that catches it.
 *  3. **A `Long` anywhere in the event pipeline.** `Double.NaN.toLong()` is `0L` in Kotlin, so
 *     one careless conversion renders polar night as 1970-01-01; `roundToLong()` throws on NaN
 *     instead, which is a crash rather than a lie but still wrong. [Instant]? is the only
 *     representation of an event time, and [fromJulian] is the single seam where a NaN is
 *     allowed to become a null.
 *
 * One genuine platform difference is worth knowing about before it is mistaken for a bug. V8
 * and the JVM do not produce bit-identical results for `sin` and `cos`; sampled over 400
 * positions the two disagree by at most one unit in the last place, roughly 1e-14 degrees.
 * That is invisible in [times] because [fromJulian] truncates to whole milliseconds, which is
 * eleven orders of magnitude coarser, and the corpus does match to the millisecond on all 290
 * of its instants. It is visible in the last bits of [position], so a test comparing altitudes
 * against JavaScript has to allow a small epsilon while a test comparing instants must not.
 * Use [kotlin.math] (which is `java.lang.Math`) rather than `StrictMath`: the goldens were
 * verified against that choice.
 *
 * The moon half of the library (`getMoonPosition`, `getMoonIllumination`, `getMoonTimes`) and
 * `astroRefraction` are not ported: SunApp does not surface them.
 */
object SunCalc {

    // ---------------------------------------------------------------------------------------
    // Constants, transcribed. The minified source calls these E, I, k, x, S and z.
    // ---------------------------------------------------------------------------------------

    /** Degrees to radians. `E` upstream. */
    private const val RAD = PI / 180.0

    /** Milliseconds in a day. `I` upstream. */
    private const val DAY_MS = 86_400_000.0

    /** Julian day number of the Unix epoch. `k` upstream. */
    private const val J1970 = 2_440_588.0

    /** Julian day number of J2000.0. `x` upstream. */
    private const val J2000 = 2_451_545.0

    /**
     * Leap-second-free fudge term in the transit approximation. `S` upstream.
     *
     * Incidentally the reason the julian-cycle tie almost never occurs: it drags the rounding
     * argument off the half-integer at all but one four-decimal longitude.
     */
    private const val J0 = 9e-4

    /**
     * Obliquity of the ecliptic, held constant at its J2000 value.
     *
     * It genuinely drifts, by roughly 0.013 deg per century, and correcting for that is the
     * classic "obvious improvement" that fails every golden row. Upstream freezes it; so do we.
     */
    private const val OBLIQUITY = 23.4397 * RAD

    /**
     * The rise/set pairs in upstream's `SunCalc.times` order.
     *
     * The order matters only for reproducibility of any future debugging trace, since each
     * pair is solved independently, but keeping it identical costs nothing. The angle is read
     * from the enum rather than repeated here so there is exactly one place to be wrong.
     */
    private val RISE_SET_PAIRS = listOf(
        SolarEvent.SUNRISE to SolarEvent.SUNSET,
        SolarEvent.SUNRISE_END to SolarEvent.SUNSET_START,
        SolarEvent.DAWN to SolarEvent.DUSK,
        SolarEvent.NAUTICAL_DAWN to SolarEvent.NAUTICAL_DUSK,
        SolarEvent.NIGHT_END to SolarEvent.NIGHT,
        SolarEvent.GOLDEN_HOUR_END to SolarEvent.GOLDEN_HOUR,
    )

    // ---------------------------------------------------------------------------------------
    // Public surface
    // ---------------------------------------------------------------------------------------

    /**
     * Every solar event for the solar day containing [date] at the given coordinates.
     *
     * The returned map always carries all fourteen [SolarEvent] keys, in enum order. A null
     * value means the event does not occur that day, which is upstream's NaN-valued `Date`
     * and not an error: at Longyearbyen in December there is simply no sunrise. [SolarEvent
     * .SOLAR_NOON] and [SolarEvent.NADIR] are the two keys that are non-null for any finite
     * input, because they never route through [hourAngle]'s `acos`.
     *
     * [date] is anchored at **12:00 UTC**, which is the rule `app.js` section 9.2 uses. This
     * is not cosmetic. [julianCycle] picks which solar day to solve for from the anchor
     * instant, so anchoring at local midnight would select the neighbouring day for locations
     * far enough east or west, and the two surfaces would return different answers for the
     * same calendar date. Note the consequence: because the solar day is centred on the
     * location's own noon rather than on a UTC date, individual events legitimately fall on
     * the adjacent UTC calendar day. NADIR does so at every longitude east of about 0 deg,
     * and at Suva or Apia even sunrise does. That is correct output, not drift.
     */
    fun times(date: LocalDate, latDeg: Double, lonDeg: Double): Map<SolarEvent, Instant?> =
        times(date.atTime(12, 0).toInstant(ZoneOffset.UTC), latDeg, lonDeg)

    /**
     * Every solar event for the solar day containing the instant [anchor].
     *
     * This is upstream's actual `getTimes(date, lat, lng)` signature, kept because the anchor
     * instant is what the algorithm consumes and hiding it would make the day-selection
     * behaviour described on the [times] overload above invisible. Note the three-argument
     * form is deliberate: SunCalc 1.9.0 added a fourth `height` parameter, and adding it here
     * would change every horizon-crossing result.
     */
    fun times(anchor: Instant, latDeg: Double, lonDeg: Double): Map<SolarEvent, Instant?> {
        val lw = RAD * -lonDeg
        val phi = RAD * latDeg
        val d = toDays(anchor)

        // The frozen geometry for this one solar day. Upstream computes the sun's mean anomaly
        // and ecliptic longitude ONCE, at approximate transit, and reuses them for all twelve
        // crossings rather than iterating each event to convergence. Re-solving per event is
        // the third "obvious improvement" that breaks parity.
        val n = julianCycle(d, lw)
        val ds = approxTransit(0.0, lw, n)
        val m = solarMeanAnomaly(ds)
        val l = eclipticLongitude(m)
        val dec = declination(l, 0.0)
        val jNoon = solarTransitJ(ds, m, l)

        val slots = arrayOfNulls<Instant>(SolarEvent.entries.size)
        slots[SolarEvent.SOLAR_NOON.ordinal] = fromJulian(jNoon)
        slots[SolarEvent.NADIR.ordinal] = fromJulian(jNoon - 0.5)

        for ((rise, set) in RISE_SET_PAIRS) {
            // Non-null by construction: RISE_SET_PAIRS only holds angle-defined events.
            val h = rise.altitudeDeg!! * RAD
            val jSet = getSetJ(h, lw, phi, dec, n, m, l)
            // The rise is the set mirrored about transit, not solved separately. When jSet is
            // NaN this is NaN too, so a pair is always absent together.
            val jRise = jNoon - (jSet - jNoon)
            slots[rise.ordinal] = fromJulian(jRise)
            slots[set.ordinal] = fromJulian(jSet)
        }

        // LinkedHashMap rather than EnumMap: EnumMap does accept null values, but a plain
        // LinkedHashMap makes "all fourteen keys are present, some map to null" obvious to
        // anyone reading a debugger, and iteration order is pinned to the enum either way.
        val result = LinkedHashMap<SolarEvent, Instant?>(SolarEvent.entries.size)
        for (event in SolarEvent.entries) result[event] = slots[event.ordinal]
        return result
    }

    /**
     * The sun's altitude and azimuth at an exact instant.
     *
     * Unlike [times] this samples the sun's true position rather than solving for a crossing,
     * so it never produces a NaN for a finite input. That property is what makes it the right
     * tool for classifying a polar day: see [DayKindCalculator].
     *
     * Upstream applies no atmospheric refraction here. The -0.833 deg in [SolarEvent] already
     * carries the refraction allowance for the horizon crossings, so adding a refraction term
     * to this function would double-count it.
     */
    fun position(at: Instant, latDeg: Double, lonDeg: Double): SolarPosition {
        val lw = RAD * -lonDeg
        val phi = RAD * latDeg
        val d = toDays(at)
        val m = solarMeanAnomaly(d)
        val l = eclipticLongitude(m)
        val dec = declination(l, 0.0)
        val ra = rightAscension(l, 0.0)
        val h = siderealTime(d, lw) - ra
        return SolarPosition(
            altitudeRad = altitude(h, phi, dec),
            azimuthRad = azimuth(h, phi, dec),
        )
    }

    // ---------------------------------------------------------------------------------------
    // Date and julian-day conversions
    // ---------------------------------------------------------------------------------------

    /** Upstream `toJulian`. Kept as its own step so the subtraction in [toDays] rounds identically. */
    private fun toJulian(at: Instant): Double =
        at.toEpochMilli() / DAY_MS - 0.5 + J1970

    /** Upstream `toDays`: days since J2000.0. */
    private fun toDays(at: Instant): Double = toJulian(at) - J2000

    /**
     * Upstream `fromJulian`, and the one and only place a NaN turns into a null.
     *
     * The truncating `toLong()` reproduces JavaScript's TimeClip, which discards the fraction
     * towards zero rather than rounding. Do not "fix" it to `roundToLong()`: that both shifts
     * results by up to half a millisecond against the corpus and throws on the NaN input this
     * function exists to absorb.
     */
    private fun fromJulian(j: Double): Instant? =
        if (j.isNaN()) null else Instant.ofEpochMilli(((j + 0.5 - J1970) * DAY_MS).toLong())

    // ---------------------------------------------------------------------------------------
    // General sun calculations
    // ---------------------------------------------------------------------------------------

    /** Upstream `rightAscension`. */
    private fun rightAscension(l: Double, b: Double): Double =
        atan2(sin(l) * cos(OBLIQUITY) - tan(b) * sin(OBLIQUITY), cos(l))

    /** Upstream `declination`. */
    private fun declination(l: Double, b: Double): Double =
        asin(sin(b) * cos(OBLIQUITY) + cos(b) * sin(OBLIQUITY) * sin(l))

    /** Upstream `azimuth`. Measured from south, see [SolarPosition]. */
    private fun azimuth(h: Double, phi: Double, dec: Double): Double =
        atan2(sin(h), cos(h) * sin(phi) - tan(dec) * cos(phi))

    /** Upstream `altitude`. */
    private fun altitude(h: Double, phi: Double, dec: Double): Double =
        asin(sin(phi) * sin(dec) + cos(phi) * cos(dec) * cos(h))

    /** Upstream `siderealTime`. */
    private fun siderealTime(d: Double, lw: Double): Double =
        RAD * (280.16 + 360.9856235 * d) - lw

    /** Upstream `solarMeanAnomaly`. */
    private fun solarMeanAnomaly(d: Double): Double =
        RAD * (357.5291 + 0.98560028 * d)

    /**
     * Upstream `eclipticLongitude`.
     *
     * The three sine terms are the equation of the centre truncated at the third harmonic, and
     * the trailing `+ PI` converts the sun's heliocentric longitude to the geocentric one.
     */
    private fun eclipticLongitude(m: Double): Double {
        val c = RAD * (1.9148 * sin(m) + 0.02 * sin(2 * m) + 0.0003 * sin(3 * m))
        val p = 102.9372 * RAD
        return m + c + p + PI
    }

    // ---------------------------------------------------------------------------------------
    // Sun-times calculations
    // ---------------------------------------------------------------------------------------

    /**
     * Upstream `julianCycle`: which solar day, counted from J2000, the anchor falls in.
     *
     * `floor(x + 0.5)` is written out rather than delegated to [kotlin.math.round] on purpose.
     * See the class KDoc, temptation 1: the two agree everywhere except at an exact tie, and
     * at that tie they disagree by a whole day.
     */
    private fun julianCycle(d: Double, lw: Double): Double =
        floor(d - J0 - lw / (2 * PI) + 0.5)

    /** Upstream `approxTransit`. */
    private fun approxTransit(ht: Double, lw: Double, n: Double): Double =
        J0 + (ht + lw) / (2 * PI) + n

    /** Upstream `solarTransitJ`: approximate transit corrected by the equation of time. */
    private fun solarTransitJ(ds: Double, m: Double, l: Double): Double =
        J2000 + ds + 0.0053 * sin(m) - 0.0069 * sin(2 * l)

    /**
     * Upstream `hourAngle`: how far from transit the sun sits at altitude [h].
     *
     * **Returns NaN when the sun never reaches [h] on that day, and that is the feature.**
     * The argument to `acos` leaves [-1, 1] precisely when the requested altitude lies outside
     * the day's altitude range, which is the definition of polar night (for a rise angle) or
     * midnight sun (for a set angle). Clamping the argument would replace "no sunrise" with
     * "sunrise exactly at solar noon", every day, for months. See the class KDoc, temptation 2.
     */
    private fun hourAngle(h: Double, phi: Double, d: Double): Double =
        acos((sin(h) - sin(phi) * sin(d)) / (cos(phi) * cos(d)))

    /** Upstream `getSetJ`: the julian date of the setting crossing at altitude [h]. */
    private fun getSetJ(
        h: Double,
        lw: Double,
        phi: Double,
        dec: Double,
        n: Double,
        m: Double,
        l: Double,
    ): Double {
        val w = hourAngle(h, phi, dec)
        val a = approxTransit(w, lw, n)
        return solarTransitJ(a, m, l)
    }
}
