package no.stormberry.sunapp.cities

import java.io.File
import java.io.InputStreamReader

/**
 * Locates and parses the real shipped catalogue for the tests in this package.
 *
 * The tests run against `SunApp/data/cities.tsv` itself rather than a trimmed
 * fixture, and that is the point of them. A fixture would prove the parser can
 * read a file the test author wrote; only the real file proves it can read what
 * `update_cities.py` emits, catches a format change on the next regeneration,
 * and lets the local-places assertions mean what they say. It costs a few
 * milliseconds and no maintenance.
 *
 * The file is not copied into `src/test/resources` because that would be a
 * second 909 KiB copy of a file whose entire design goal is to have exactly one
 * copy per repository.
 */
object TestCatalogue {

    /**
     * The catalogue path, found by walking up from the working directory.
     *
     * Gradle runs unit tests with the working directory set to the module
     * directory, but that is a default rather than a contract, and IDE runners
     * disagree with it. Walking up until `data/cities.tsv` appears works from
     * `app/`, from `android/` and from the repository root alike, and fails
     * with a legible message rather than a bare `FileNotFoundException` if the
     * tree is not what it should be.
     */
    val file: File by lazy {
        var dir: File? = File(System.getProperty("user.dir") ?: ".").absoluteFile
        while (dir != null) {
            val candidate = File(dir, "data/cities.tsv")
            if (candidate.isFile) return@lazy candidate
            dir = dir.parentFile
        }
        error(
            "Could not find data/cities.tsv above ${System.getProperty("user.dir")}. " +
                "It is generated by SunApp/update_cities.py and committed to the repository."
        )
    }

    /** Parsed once and shared, so eight tests do not pay eight parses. */
    val table: CityTable by lazy { parseFile() }

    /** A fresh parse, for the tests that measure one. */
    fun parseFile(): CityTable =
        file.inputStream().use { CityTable.parse(InputStreamReader(it, Charsets.UTF_8)) }

    /** The single entry named [name], failing loudly if it is absent or ambiguous. */
    fun city(name: String): City {
        val matches = table.cities.filter { it.name == name }
        check(matches.size == 1) { "Expected exactly one city named '$name', found ${matches.size}" }
        return matches.single()
    }
}
