package no.stormberry.sunapp.solar

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.LocalDate

/**
 * Proves the Kotlin classifier and the shipped JavaScript one agree.
 *
 * [DayKindCalculator] is documented as a transcription of `app.js` section 9.4,
 * and the owner's decision is that sun.stormberry.as and the APK must never
 * disagree about whether a day is polar. A comment asserting that is not a
 * guarantee; this is.
 *
 * `daykind-parity.csv` is generated by running the classifier from `app.js`,
 * verbatim, against the bundled `suncalc.js` under Node, across six latitudes
 * and sixty dates each. Regenerate it whenever either classifier changes: if
 * this test then fails, the two surfaces have drifted and one of them is wrong.
 *
 * The latitudes are chosen so the corpus is not all one answer: Longyearbyen
 * and the North Pole supply polar night and midnight sun, Tromso supplies the
 * awkward middle, and Bergen, Ushuaia and Singapore supply ordinary days in
 * both hemispheres.
 */
class DayKindParityTest {

    private data class Row(
        val place: String,
        val lat: Double,
        val lon: Double,
        val date: LocalDate,
        val expected: DayKind,
    )

    private fun corpus(): List<Row> {
        val text = checkNotNull(javaClass.getResourceAsStream("/daykind-parity.csv")) {
            "daykind-parity.csv missing from test resources"
        }.bufferedReader().readText()

        return text.trim().lines().drop(1).map { line ->
            val f = line.split(",")
            require(f.size == 5) { "Malformed parity row: $line" }
            Row(f[0], f[1].toDouble(), f[2].toDouble(), LocalDate.parse(f[3]), DayKind.valueOf(f[4]))
        }
    }

    @Test
    fun `the corpus covers all three kinds, so a pass is not vacuous`() {
        val kinds = corpus().map { it.expected }.toSet()
        assertEquals(
            "A parity corpus that never exercises a branch cannot detect a broken one",
            DayKind.entries.toSet(),
            kinds,
        )
    }

    @Test
    fun `every day classifies the same as the web app`() {
        val rows = corpus()
        val mismatches = rows.mapNotNull { row ->
            val actual = DayKindCalculator.of(row.date, row.lat, row.lon)
            if (actual == row.expected) null
            else "${row.place} ${row.date}: web says ${row.expected}, Kotlin says $actual"
        }
        assertTrue(
            "${mismatches.size} of ${rows.size} days disagree between app.js and DayKindCalculator:\n" +
                mismatches.take(10).joinToString("\n"),
            mismatches.isEmpty(),
        )
    }
}
