package no.stormberry.sunapp.solar

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.InputStreamReader
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneOffset
import kotlin.math.abs

/**
 * Asserts the Kotlin port against `suncalc-golden.csv`, a corpus produced by running the
 * repository's own `suncalc.js` under Node (`tools/gen-solar-golden.js`).
 *
 * The corpus is the reference, not an almanac, and that is the point. SunCalc 1.8.0 is an
 * approximation, so an almanac would flag the *library's* error as a port bug and would keep
 * flagging it forever. What has to be preserved is that the APK and sun.stormberry.as return
 * the same instant for the same input, to the millisecond, including the instants that are
 * arguably a little wrong.
 *
 * Regenerate with `node tools/gen-solar-golden.js` after any deliberate change to
 * `suncalc.js`, and never by hand.
 */
class SunCalcGoldenTest {

    private data class GoldenRow(
        val caseId: String,
        val description: String,
        val latDeg: Double,
        val lonDeg: Double,
        val date: LocalDate,
        val event: SolarEvent,
        /** Null encodes the corpus's literal `NONE`, meaning the event does not occur. */
        val expected: Instant?,
    ) {
        /** Enough to identify a failing row in a test report without opening the CSV. */
        fun where(): String = "$caseId $event ($description, $latDeg/$lonDeg, $date)"
    }

    /**
     * One computed day, cached so a 350-row sweep costs 25 calls rather than 350. The port is
     * cheap enough that this is comfort rather than necessity, but it also means every row of
     * a case is asserted against one map, which is what the map contract actually promises.
     */
    private val computed = HashMap<String, Map<SolarEvent, Instant?>>()

    private fun timesFor(row: GoldenRow): Map<SolarEvent, Instant?> =
        computed.getOrPut(row.caseId) { SunCalc.times(row.date, row.latDeg, row.lonDeg) }

    private val rows: List<GoldenRow> by lazy { loadCorpus() }

    private fun loadCorpus(): List<GoldenRow> {
        val stream = requireNotNull(javaClass.getResourceAsStream("/$CORPUS")) {
            "$CORPUS is missing from the test resources. It is generated by " +
                "tools/gen-solar-golden.js and committed; it is not built on demand."
        }
        val lines = InputStreamReader(stream, Charsets.UTF_8).use { it.readLines() }
        assertEquals(
            "The corpus header has changed shape, so the column order below is no longer safe",
            HEADER,
            lines.first(),
        )
        return lines.drop(1).filter { it.isNotBlank() }.map { line ->
            // A plain split is safe only because the generator asserts no field contains a
            // comma. If that guard is ever removed this parser has to become a real one.
            val f = line.split(",")
            assertEquals("Malformed corpus row: $line", 7, f.size)
            GoldenRow(
                caseId = f[0],
                description = f[1],
                latDeg = f[2].toDouble(),
                lonDeg = f[3].toDouble(),
                date = LocalDate.parse(f[4]),
                event = SolarEvent.valueOf(f[5]),
                expected = if (f[6] == ABSENT) null else Instant.parse(f[6]),
            )
        }
    }

    @Test
    fun `corpus is the shape the generator promises`() {
        assertEquals("Expected 25 cases x 14 events", 350, rows.size)
        assertEquals("Every case must cover every event", 25, rows.map { it.caseId }.distinct().size)
        for ((caseId, caseRows) in rows.groupBy { it.caseId }) {
            assertEquals(
                "$caseId does not cover all fourteen events",
                SolarEvent.entries.toSet(),
                caseRows.map { it.event }.toSet(),
            )
        }
    }

    /**
     * The contracted assertion: every instant within one second.
     *
     * A second is generous on purpose, as the tolerance a reviewer can argue about without
     * reading the port. The tighter lock lives in the millisecond test below; if that one
     * fails while this one passes, the change is a rounding seam. If both fail, the algebra
     * has moved.
     */
    @Test
    fun `every golden instant matches within one second`() {
        val failures = rows.filter { it.expected != null }.mapNotNull { row ->
            val actual = timesFor(row)[row.event]
            when {
                actual == null -> "${row.where()}: expected ${row.expected}, port says the event does not occur"
                abs(actual.toEpochMilli() - row.expected!!.toEpochMilli()) > 1_000L ->
                    "${row.where()}: expected ${row.expected}, got $actual"
                else -> null
            }
        }
        assertTrue(
            "${failures.size} of ${rows.count { it.expected != null }} instants are off by more " +
                "than a second:\n" + failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    /**
     * The real lock. Literal transcription reproduces the JavaScript exactly, because both
     * sides are IEEE-754 doubles evaluated in the same order and both truncate towards zero at
     * the millisecond seam. Any drift here is a transcription error, not a platform difference.
     */
    @Test
    fun `every golden instant matches to the millisecond`() {
        val failures = rows.filter { it.expected != null }.mapNotNull { row ->
            val actual = timesFor(row)[row.event]
            if (actual == row.expected) null else {
                val delta = actual?.let { it.toEpochMilli() - row.expected!!.toEpochMilli() }
                "${row.where()}: expected ${row.expected}, got $actual (delta ${delta ?: "n/a"} ms)"
            }
        }
        assertTrue(
            "${failures.size} instants are not millisecond-exact:\n" + failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    /**
     * Absence is asserted per key, not per day.
     *
     * "Any NaN means polar" is the bug this catches. The corpus contains days where sunrise
     * resolves and nautical twilight does not (G04), days where sunrise resolves and only the
     * golden-hour keys do not (G21), and days where the sunrise key resolves while the
     * sunrise-end key does not (G10). A port that collapses absence to a single per-day flag
     * passes a sunrise-only suite and fails all three of those.
     */
    @Test
    fun `every golden absence is a null and never an epoch instant`() {
        val failures = rows.filter { it.expected == null }.mapNotNull { row ->
            val actual = timesFor(row)[row.event] ?: return@mapNotNull null
            val hint = if (actual.toEpochMilli() == 0L) {
                " (epoch zero: a NaN has been converted with toLong() somewhere)"
            } else {
                ""
            }
            "${row.where()}: expected no event, got $actual$hint"
        }
        assertTrue(
            "${failures.size} absent events came back non-null:\n" + failures.joinToString("\n"),
            failures.isEmpty(),
        )
    }

    @Test
    fun `times always returns all fourteen keys`() {
        val times = SunCalc.times(LocalDate.of(2026, 12, 21), 78.2233, 15.6469)
        assertEquals(SolarEvent.entries.size, times.size)
        assertEquals(
            "Iteration order is part of the contract, since callers render in this order",
            SolarEvent.entries.toList(),
            times.keys.toList(),
        )
    }

    // -------------------------------------------------------------------------------------
    // Named pins. Each of these is already covered by the sweeps above; they exist so that a
    // regression reports which trap was sprung rather than dumping fourteen anonymous rows.
    // -------------------------------------------------------------------------------------

    /**
     * G13: Longyearbyen at midsummer. All twelve angle events absent, both transits present.
     *
     * This is the pin for a `coerceIn(-1.0, 1.0)` on the `acos` argument in `hourAngle`. Add
     * that one defensive line and every key below becomes a fake crossing at solar noon.
     */
    @Test
    fun `G13 Longyearbyen midsummer has no angle events but keeps both transits`() {
        val times = SunCalc.times(LocalDate.of(2026, 6, 21), 78.2233, 15.6469)
        for (event in SolarEvent.entries.filter { it.altitudeDeg != null }) {
            assertNull("$event should not occur during midnight sun", times[event])
        }
        assertNotNull(times[SolarEvent.SOLAR_NOON])
        assertNotNull(times[SolarEvent.NADIR])
    }

    /**
     * G12: Longyearbyen in deep polar night, the complement of G13.
     *
     * There is no sunrise, yet nautical and astronomical twilight are perfectly real: the sun
     * does reach -12 and -18 deg, it simply never comes back up to -0.833.
     */
    @Test
    fun `G12 Longyearbyen polar night has no sunrise but real deep twilight`() {
        val times = SunCalc.times(LocalDate.of(2026, 12, 21), 78.2233, 15.6469)
        assertNull(times[SolarEvent.SUNRISE])
        assertNull(times[SolarEvent.SUNSET])
        assertNotNull(times[SolarEvent.NAUTICAL_DAWN])
        assertNotNull(times[SolarEvent.NIGHT_END])
    }

    /**
     * G10: Tromso on 2026-01-15. The sun clears -0.833 deg for about twenty-four minutes but
     * never reaches -0.3, so SUNRISE resolves while SUNRISE_END does not.
     *
     * Any code that treats sunrise as implying sunrise-end computes a negative interval here.
     */
    @Test
    fun `G10 Tromso has a sunrise whose disc never fully clears the horizon`() {
        val times = SunCalc.times(LocalDate.of(2026, 1, 15), 69.6492, 18.9553)
        assertNotNull(times[SolarEvent.SUNRISE])
        assertNotNull(times[SolarEvent.SUNSET])
        assertNull(times[SolarEvent.SUNRISE_END])
        assertNull(times[SolarEvent.SUNSET_START])
    }

    /**
     * G25: the julian-cycle rounding canary, and the only row in the corpus that discriminates.
     *
     * At longitude -179.6760 on a date whose day counter is even, the rounding argument lands
     * on an exact half. JavaScript's round-half-up and Kotlin's round-half-to-even then choose
     * different solar days, moving solar noon by twenty-four hours. Every other case in the
     * corpus passes under either rule, so this is the whole of the protection.
     */
    @Test
    fun `G25 the antimeridian rounding tie picks the same solar day as JavaScript`() {
        val row = rows.single { it.caseId == "G25" && it.event == SolarEvent.SOLAR_NOON }
        val actual = SunCalc.times(row.date, row.latDeg, row.lonDeg)[SolarEvent.SOLAR_NOON]
        assertEquals(
            "julianCycle must use floor(x + 0.5), not kotlin.math.round",
            row.expected,
            actual,
        )
    }

    /**
     * G24: Reykjavik at midsummer. Atlantic/Reykjavik is UTC+0 all year, so there is no offset
     * to hide behind and the sunset for 21 June lands on 22 June in UTC.
     *
     * Asserted here because a well-meaning "keep every event inside the requested UTC date"
     * correction would look like a tidy-up and would silently shift the alarm anchor.
     */
    @Test
    fun `G24 Reykjavik sunset legitimately falls on the following UTC day`() {
        val sunset = SunCalc.times(LocalDate.of(2026, 6, 21), 64.1466, -21.9426)[SolarEvent.SUNSET]
        assertNotNull(sunset)
        assertEquals(
            "The sunset for 21 June is a 22 June instant, in a zone that is UTC+0 all year",
            LocalDate.of(2026, 6, 22),
            sunset!!.atZone(ZoneOffset.UTC).toLocalDate(),
        )
    }

    private companion object {
        const val CORPUS = "suncalc-golden.csv"
        const val ABSENT = "NONE"
        const val HEADER = "case_id,description,lat,lon,date,event,expected_utc"
    }
}
