#!/usr/bin/env python3
"""Regenerate the adaptive-icon foreground from the web app's favicon.svg.

Unlike the Stormberry lockup, which exists only as a raster and has to be
traced, SunApp's favicon is real vector: a gradient-filled disc and eight
rays. So this converts geometry directly rather than tracing, and the result
is exact rather than an approximation.

    python3 tools/build-sunapp-icon.py

Two lint checks, both errors in this build, shape the output: VectorPath
rejects a pathData over 3000 characters, and VectorRaster rejects an intrinsic
dimension over 200dp. Neither is close here.

Geometry: the source is a 64x64 viewBox with the disc at r=14 and rays running
from r~20 to r~29. Adaptive icons are 108x108 with a 66x66 safe zone, and the
outer third can be clipped by the launcher's mask. The disc is therefore kept
comfortably inside the safe zone and the rays are allowed to reach just past
it, which is what makes it still read as a sun after a circular mask crops the
corners.
"""
import math
import os

CENTRE = 54.0
DISC_R = 15.0     # safe zone is r=33; the disc alone must survive any mask
RAY_IN = 22.0
RAY_OUT = 32.0
RAY_W = 3.4

RES = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "app", "src", "main", "res", "drawable")
OUT = os.path.join(RES, "ic_launcher_foreground.xml")
# The same mark at in-app scale. The launcher version is inset for the adaptive
# safe zone, which looks lost inside a Compose layout, so this one fills its box.
OUT_APP = os.path.join(RES, "ic_app_logo.xml")


def ray_path(angle_deg):
    a = math.radians(angle_deg)
    dx, dy = math.cos(a), math.sin(a)
    x1, y1 = CENTRE + dx * RAY_IN, CENTRE + dy * RAY_IN
    x2, y2 = CENTRE + dx * RAY_OUT, CENTRE + dy * RAY_OUT
    return f"M{x1:.1f},{y1:.1f}L{x2:.1f},{y2:.1f}"


def main():
    rays = "".join(ray_path(a) for a in range(0, 360, 45))
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by tools/build-sunapp-icon.py from the web app's favicon.svg.
  Do not hand-edit: rerun the script so the launcher icon and sun.stormberry.as
  cannot drift apart.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <!-- The rays, drawn first so the disc overlaps their inner ends cleanly. -->
    <path
        android:pathData="{rays}"
        android:strokeWidth="{RAY_W}"
        android:strokeLineCap="round">
        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt" name="android:strokeColor">
            <gradient
                android:type="linear"
                android:startX="22" android:startY="22"
                android:endX="86" android:endY="86">
                <item android:offset="0" android:color="#FFFFD700" />
                <item android:offset="1" android:color="#FFFF6B35" />
            </gradient>
        </aapt:attr>
    </path>

    <!--
      Radial gradient lifted from favicon.svg's sunGrad, including its off-centre
      focus at 40%/35%, which is what gives the disc its lit-from-upper-left look
      rather than a flat blob.
    -->
    <path
        android:pathData="M{CENTRE},{CENTRE - DISC_R}
            a{DISC_R},{DISC_R} 0 1,0 0.1,0 Z">
        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt" name="android:fillColor">
            <gradient
                android:type="radial"
                android:centerX="{CENTRE - DISC_R * 0.2:.1f}"
                android:centerY="{CENTRE - DISC_R * 0.3:.1f}"
                android:gradientRadius="{DISC_R * 1.3:.1f}">
                <item android:offset="0" android:color="#FFFFF7A1" />
                <item android:offset="0.6" android:color="#FFFFB347" />
                <item android:offset="1" android:color="#FFFF6B35" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
'''
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(xml)
    # In-app variant: same geometry, 64dp box, no safe-zone inset.
    app_xml = (xml.replace('android:width="108dp"', 'android:width="64dp"')
                  .replace('android:height="108dp"', 'android:height="64dp"')
                  .replace("GENERATED by tools/build-sunapp-icon.py from the web app's favicon.svg.",
                           "GENERATED by tools/build-sunapp-icon.py. In-app variant of the sun mark."))
    with open(OUT_APP, "w", encoding="utf-8") as fh:
        fh.write(app_xml)
    longest = max(len(rays), 60)
    print(f"wrote {OUT}")
    print(f"wrote {OUT_APP}")
    print(f"longest pathData: {longest} chars (VectorPath lint limit is 3000)")


if __name__ == "__main__":
    main()
