package no.stormberry.sunapp.cities

/**
 * One entry of the shared Stormberry Labs city catalogue.
 *
 * The catalogue is generated by `SunApp/update_cities.py` and shipped to nine
 * sibling web apps as `cities.js` and to this app as `assets/data/cities.tsv`.
 * The shape below is deliberately the same shape the JavaScript decoder builds,
 * field for field, because the two search implementations have to agree: a
 * person who finds a place on sunapp.stormberry.no and then cannot find it on
 * their phone reports that as a bug, and rightly so.
 *
 * Three of the eight fields exist purely so that search never has to fold a
 * string in the inner loop. Folding 25,007 names on every keystroke is roughly
 * a hundred times the work of comparing 25,007 already-folded ones, so the
 * folds are precomputed: [fold] and [alt] by the generator, [cfold] once per
 * country palette entry at parse time.
 *
 * @property name the display name, accents and all, exactly as GeoNames spells
 *   it locally. US and Brazilian entries carry a state suffix ("Austin, TX")
 *   because the catalogue holds several same-named places per country.
 * @property fold [name] reduced by [foldQuery]: NFD-stripped, lowercased and
 *   transliterated. Never blank. The TSV omits it when it equals
 *   `name.lowercase()`, and the parser fills it back in.
 * @property alt the folded English exonym, blank when there is none or when it
 *   adds nothing over [fold]. This is what makes "gothenburg" find Göteborg and
 *   "cologne" find Köln, neither of which a person typing English would guess
 *   the local spelling of.
 * @property country display country name from the palette. "USA" and "UK"
 *   rather than the GeoNames long forms.
 * @property cfold [country] reduced by [foldQuery], so that typing "cote
 *   d'ivoire" matches "Côte d'Ivoire". Shared between every city of a country.
 * @property lat degrees north, positive. Decoded from a lossless 1e4 integer;
 *   the upstream source carries exactly four decimals.
 * @property lon degrees east, positive.
 * @property tz IANA zone id, for example "Europe/Oslo". Every value in the
 *   shipped catalogue satisfies `ZoneId.of()`, which a unit test asserts so
 *   that a tzdb link retirement is caught here rather than by a user whose
 *   alarm silently stops firing.
 */
data class City(
    val name: String,
    val fold: String,
    val alt: String,
    val country: String,
    val cfold: String,
    val lat: Double,
    val lon: Double,
    val tz: String,
)
