package no.stormberry.sunapp.ui

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import no.stormberry.sunapp.R

/**
 * SunApp's palette, lifted verbatim from the web app's style.css custom
 * properties so the APK and sun.stormberry.as look like one product.
 *
 * Note this is NOT the same palette as UsernameGenerator, which the Android
 * scaffold was copied from: SunApp uses a deep-blue night sky with gold and
 * orange sun accents, not the indigo house default. Keep it in step with
 * style.css rather than with the sibling app.
 *
 * Dark-only by design. isSystemInDarkTheme() is deliberately not consulted
 * because a light variant of this palette does not exist.
 */
object Sun {
    /** --bg-base */
    val Background = Color(0xFF080C18)
    /** --bg-surface */
    val Surface = Color(0xFF0E1628)
    /** --bg-card, rgba(14, 22, 48, 0.72) */
    val Card = Color(0xB80E1630)
    /** --bg-card-hover, rgba(22, 34, 70, 0.85) */
    val CardHover = Color(0xD9162246)
    /** --border, rgba(255, 255, 255, 0.08) */
    val Border = Color(0x14FFFFFF)
    /** --border-active, rgba(255, 215, 0, 0.35) */
    val BorderActive = Color(0x59FFD700)

    /** --text-primary */
    val TextPrimary = Color(0xFFF0F4FF)
    /** --text-secondary */
    val TextSecondary = Color(0xFF8A9BCA)
    /** --text-muted */
    val TextMuted = Color(0xFF4A5580)

    /** --accent-gold, the sunrise/sunset accent */
    val Gold = Color(0xFFFFD700)
    /** --accent-orange */
    val Orange = Color(0xFFFF8C42)
    /** --accent-rose */
    val Rose = Color(0xFFFF6B6B)
    /** --accent-blue */
    val Blue = Color(0xFF4FC3F7)
    /** --accent-noon, used for solar noon */
    val Noon = Color(0xFFFFF176)
}

private val SunColors = darkColorScheme(
    primary = Sun.Gold,
    onPrimary = Sun.Background,
    secondary = Sun.Blue,
    onSecondary = Sun.Background,
    tertiary = Sun.Orange,
    background = Sun.Background,
    onBackground = Sun.TextPrimary,
    surface = Sun.Surface,
    onSurface = Sun.TextPrimary,
    surfaceVariant = Sun.Card,
    onSurfaceVariant = Sun.TextSecondary,
    outline = Sun.Border,
    error = Sun.Rose,
)

/**
 * Inter, the typeface sun.stormberry.as self-hosts from fonts/inter/, so the APK and the site
 * set text in the same face. Four static instances of that same InterVariable.woff2, one per
 * weight this app uses, live in res/font and are regenerated by tools/build-inter-fonts.py.
 * Bundled in the APK: no downloadable-fonts provider, no network. A weight not listed here
 * would be faked by synthesis, so add an instance before using one.
 *
 * Clock readings and coordinates stay FontFamily.Monospace where the screens ask for it, so
 * the digits line up; everything else is Inter.
 */
val Inter = FontFamily(
    Font(R.font.inter_regular, FontWeight.Normal),
    Font(R.font.inter_medium, FontWeight.Medium),
    Font(R.font.inter_semibold, FontWeight.SemiBold),
    Font(R.font.inter_bold, FontWeight.Bold),
)

/** Every Material 3 text style, set in [family]. Text with no explicit style inherits bodyLarge. */
private fun Typography.withFontFamily(family: FontFamily) = copy(
    displayLarge = displayLarge.copy(fontFamily = family),
    displayMedium = displayMedium.copy(fontFamily = family),
    displaySmall = displaySmall.copy(fontFamily = family),
    headlineLarge = headlineLarge.copy(fontFamily = family),
    headlineMedium = headlineMedium.copy(fontFamily = family),
    headlineSmall = headlineSmall.copy(fontFamily = family),
    titleLarge = titleLarge.copy(fontFamily = family),
    titleMedium = titleMedium.copy(fontFamily = family),
    titleSmall = titleSmall.copy(fontFamily = family),
    bodyLarge = bodyLarge.copy(fontFamily = family),
    bodyMedium = bodyMedium.copy(fontFamily = family),
    bodySmall = bodySmall.copy(fontFamily = family),
    labelLarge = labelLarge.copy(fontFamily = family),
    labelMedium = labelMedium.copy(fontFamily = family),
    labelSmall = labelSmall.copy(fontFamily = family),
)

private val SunTypography = Typography().withFontFamily(Inter).run {
    copy(
        displaySmall = displaySmall.copy(fontWeight = FontWeight.Bold),
        headlineSmall = headlineSmall.copy(fontWeight = FontWeight.Bold),
        titleMedium = titleMedium.copy(fontWeight = FontWeight.SemiBold),
        labelLarge = labelLarge.copy(fontWeight = FontWeight.Medium),
    )
}

@Composable
fun SunAppTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = SunColors,
        typography = SunTypography,
        content = content,
    )
}
