package no.stormberry.sunapp.alarm

import no.stormberry.sunapp.alarm.model.AlarmRule
import no.stormberry.sunapp.alarm.model.Clamp
import no.stormberry.sunapp.alarm.model.Direction
import no.stormberry.sunapp.solar.SolarEvent
import java.time.ZoneId

/**
 * Shared fixtures for the alarm tests.
 *
 * The coordinates are the same ones the golden solar corpus uses for Bergen and Longyearbyen,
 * so an expected instant here can be traced back to a row of `suncalc-golden.csv` or
 * regenerated by running the bundled `suncalc.js` under Node with the same noon-UTC anchoring
 * rule. Every expected time in these tests was produced that way rather than by running the
 * Kotlin and writing down what it said, which is the difference between a test and a
 * snapshot of the current behaviour.
 */
internal const val BERGEN_LAT = 60.3913
internal const val BERGEN_LON = 5.3221

/** Longyearbyen, the highest-latitude entry in the bundled city table and the reason the
 *  solar-noon fallback exists at all. */
internal const val LONGYEARBYEN_LAT = 78.2233
internal const val LONGYEARBYEN_LON = 15.6469

/**
 * Europe/Oslo throughout, including for Longyearbyen.
 *
 * Svalbard's own identifier, `Arctic/Longyearbyen`, is a link to `Europe/Oslo` that upstream
 * tzdb has moved into the backward-compatibility set. Using the link here would make these
 * tests fail on a future tzdb, or on the desugared database shipped to API 24 and 25, for a
 * reason that has nothing to do with the alarm engine. The link retirement is worth a test of
 * its own, and it has one, in the city table's "every zone resolves" check.
 */
internal val OSLO: ZoneId = ZoneId.of("Europe/Oslo")

/** A rule with sensible defaults, so each test names only the field it is about. */
internal fun testRule(
    id: String = "rule-1",
    label: String = "Test alarm",
    anchor: SolarEvent = SolarEvent.SUNRISE,
    direction: Direction = Direction.AT,
    offsetMinutes: Int = 0,
    latDeg: Double = BERGEN_LAT,
    lonDeg: Double = BERGEN_LON,
    zoneId: String = "Europe/Oslo",
    placeName: String = "Bergen",
    clamp: Clamp? = null,
    enabled: Boolean = true,
    ringtoneUri: String? = null,
    vibrate: Boolean = true,
): AlarmRule = AlarmRule(
    id = id,
    label = label,
    anchor = anchor,
    direction = direction,
    offsetMinutes = offsetMinutes,
    latDeg = latDeg,
    lonDeg = lonDeg,
    zoneId = zoneId,
    placeName = placeName,
    clamp = clamp,
    enabled = enabled,
    ringtoneUri = ringtoneUri,
    vibrate = vibrate,
)
