import java.io.FileInputStream
import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
}

// Signing credentials never live in this repo. Locally they come from
// android/keystore.properties (gitignored); in CI from ORG_GRADLE_PROJECT_* env vars.
// Missing credentials must not break `assembleDebug`, so everything below is optional.
val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) load(FileInputStream(keystorePropertiesFile))
}

fun signingValue(propKey: String, gradleKey: String): String? =
    keystoreProperties.getProperty(propKey) ?: providers.gradleProperty(gradleKey).orNull

val releaseStoreFile = signingValue("storeFile", "RELEASE_STORE_FILE")
val releaseStorePassword = signingValue("storePassword", "RELEASE_STORE_PASSWORD")
val releaseKeyAlias = signingValue("keyAlias", "RELEASE_KEY_ALIAS")
val releaseKeyPassword = signingValue("keyPassword", "RELEASE_KEY_PASSWORD")
val canSignRelease = releaseStoreFile != null && file(releaseStoreFile).exists()

val cityAssetsDir = layout.buildDirectory.dir("generated/assets/cities")

android {
    namespace = "no.stormberry.sunapp"
    // compileSdk is 37.1 because androidx (core-ktx 1.19.0, lifecycle 2.11.0,
    // compose 1.11.4) requires compiling against API 37 or later. targetSdk stays
    // at 36, which is what Google Play requires for new apps from 31 August 2026;
    // the two are deliberately independent.
    compileSdk = 37
    compileSdkMinor = 1

    defaultConfig {
        applicationId = "no.stormberry.sunapp"
        minSdk = 24
        targetSdk = 36
        // 1.1.0, not 1.0.0. The tree carries the alarm feature and its nine
        // install-time permissions, so a 1.0.0 label would misdescribe the
        // binary. The information-only 1.0.0 described in the plan was never
        // cut as a separate artefact; see android/README.md "Releases".
        versionCode = 2
        versionName = "1.1.0"

        // No instrumentation tests, no test runner, nothing that pulls in extra permissions.
        // Density-split PNGs are generated at build time from vectors and are a source of
        // build nondeterminism, so keep the vectors only.
        vectorDrawables.generatedDensities()
    }

    signingConfigs {
        if (canSignRelease) {
            create("release") {
                storeFile = file(releaseStoreFile!!)
                storePassword = releaseStorePassword
                keyAlias = releaseKeyAlias
                keyPassword = releaseKeyPassword
                // Pinned explicitly: AGP documents these as "if null, a default value is
                // used" without saying what that default is, so an AGP upgrade could
                // silently change what the APK carries. minSdk 24 means v1 JAR signing
                // is dead weight; v2 covers 7.0+, v3 enables key rotation later.
                enableV1Signing = false
                enableV2Signing = true
                enableV3Signing = true
                enableV4Signing = false
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (canSignRelease) signingConfig = signingConfigs.getByName("release")
        }
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    // The city catalogue is shared with the web app and with the eight sibling
    // Labs apps. One source of truth: SunApp/data/cities.tsv is generated by
    // SunApp/update_cities.py and copied into assets at build time rather than
    // duplicated here.
    sourceSets["main"].assets.directories.add(cityAssetsDir.get().asFile.absolutePath)

    buildFeatures {
        compose = true
        buildConfig = false
        resValues = false
        shaders = false
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // java.time is API 26+ and minSdk is 24, so two API levels would not have
        // it. Every solar and alarm calculation in this app is java.time, so
        // desugaring is load-bearing rather than a convenience. Note the desugar
        // library carries its OWN tzdb rather than reading Mainline updates, so on
        // API 24 and 25 a government moving a DST transition can leave the zone
        // rules stale until this dependency is bumped. See android/README.md.
        isCoreLibraryDesugaringEnabled = true
    }

    packaging {
        resources {
            excludes += setOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "DebugProbesKt.bin",
                "kotlin-tooling-metadata.json",
            )
        }
    }

    androidResources {
        // Deliberately NOT adding cities.tsv to noCompress, which is the opposite of
        // the choice UsernameGenerator made for its word lists. That file is ~900 KiB
        // raw and roughly 370 KiB deflated, AssetManager.open() inflates it
        // transparently, and the inflate cost lands inside the parse budget we were
        // going to pay anyway. Storing it uncompressed would add half a megabyte to
        // the APK for no measurable gain.
    }

    dependenciesInfo {
        // Strips the Google-signed dependency blob from the APK. It is encrypted, it is
        // not reproducible, and for an app whose whole claim is "nothing leaves the
        // device" an opaque metadata block is the wrong look.
        includeInApk = false
        includeInBundle = false
    }

    lint {
        warningsAsErrors = true
        abortOnError = true
        disable += setOf(
            // Version bumps are a deliberate, reviewed act here, not something lint
            // should fail the build over. See gradle/libs.versions.toml.
            "GradleDependency",
            "AndroidGradlePluginVersion",
            "ObsoleteLintCustomCheck",
            // targetSdk 36 is intentional. It is what Google Play requires for new
            // apps from 31 August 2026, and API 37 opts into runtime behaviour this
            // app has not been tested against. compileSdk is already 37.1.
            "OldTargetApi",
        )
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        freeCompilerArgs.addAll("-Xjvm-default=all")
    }
}

val copyCityData by tasks.registering(Copy::class) {
    description = "Copies the packed city catalogue from the repo root into app assets."
    group = "build"
    from(rootProject.file("../data")) {
        include("cities.tsv")
    }
    into(cityAssetsDir.map { it.dir("data") })
    // Deterministic ordering, so the APK is byte-reproducible across machines.
    duplicatesStrategy = DuplicatesStrategy.FAIL
}

tasks.named("preBuild") { dependsOn(copyCityData) }

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    testImplementation(libs.junit)
    // Real org.json ahead of the stubbed framework copy on the unit-test classpath only.
    // Nothing here reaches the APK: AlarmStore compiles and runs against the platform
    // org.json on a device, and this dependency exists purely so the same code can be
    // exercised by a JVM test instead of needing Robolectric or an emulator.
    testImplementation(libs.json)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.material3)

    debugImplementation(libs.androidx.compose.ui.tooling)
    implementation(libs.androidx.compose.ui.tooling.preview)
}
